# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "nprogress-0.2.0" = {
      name = "nprogress";
      packageName = "nprogress";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nprogress/-/nprogress-0.2.0.tgz";
        sha1 = "cb8f34c53213d895723fcbab907e9422adbcafb1";
      };
    };
    "phoenix-../deps/phoenix" = {
      name = "phoenix";
      packageName = "phoenix";
      version = 1;
      src = ../deps/phoenix;
    };
    "phoenix_html-../deps/phoenix_html" = {
      name = "phoenix_html";
      packageName = "phoenix_html";
      version = 1;
      src = ../deps/phoenix_html;
    };
    "phoenix_live_view-../deps/phoenix_live_view" = {
      name = "phoenix_live_view";
      packageName = "phoenix_live_view";
      version = 1;
      src = ../deps/phoenix_live_view;
    };
  };
  args = {
    name = "ts_helper_js";
    packageName = "ts_helper_js";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."nprogress-0.2.0"
      sources."phoenix-../deps/phoenix"
      sources."phoenix_html-../deps/phoenix_html"
      sources."phoenix_live_view-../deps/phoenix_live_view"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = " ";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}