name: "Build and Push"

on:
  push:
    branches:
    - main
    - dev

jobs:
  builds:
    name: Quay.io
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.1
      with: { fetch-depth: 0 }
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v8
      with:
        name: ts-helper
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#tsHelperImage
    - run: |
        docker login quay.io --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}
        set -ex
        if [[ ${{ github.ref }} == "refs/heads/master" ]]; then
          tag=latest
        else
          tag=staging
        fi
        set +ex
        docker load -i result
        docker tag quay.io/nobbz/ts-helper:g${{ github.sha }} quay.io/nobbz/ts-helper:$tag
        for img in $(docker images --filter=reference='quay.io/nobbz/*' --format '{{.Repository}}:{{.Tag}}'); do
          docker push $img
        done
